name: Deploy Streamlit App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5 pillow==10.1.0 safetensors==0.4.2 streamlit==1.29.0

      - name: Install PyTorch with CUDA 11.8
        run: |
          pip install torch==2.2.0+cu118 torchvision==0.17.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

      - name: Install remaining dependencies
        run: |
          pip install accelerate==0.25.0 diffusers==0.24.0 transformers==4.35.2 xformers==0.0.22.post7 huggingface-hub==0.20.3

      - name: Run Streamlit App
        run: |
          streamlit run app.py
